# Generated by Django 4.1 on 2022-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
